// Demo Mode Configuration
export const DEMO_MODE = false; // Set to false to use real Supabase

// Demo user for auto-login
export const DEMO_USER = {
  id: 'demo-user-001',
  email: 'demo@harmonioushabitats.com',
  full_name: 'Sunflower Lily',
  username: 'sunflowerlily',
  avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sunflower',
  bio: 'Earth-centered healer and community garden keeper. Nurturing growth through mindful connection with nature and neighbors.',
  neighborhood: 'East Austin',
  holistic_interests: ['Herbalism', 'Moon Circles', 'Plant Medicine', 'Garden Therapy', 'Earth Rituals'],
  verified: true,
  rating: 4.9,
  total_reviews: 67,
  events_attended_count: 42,
  hours_contributed: 234,
  neighbors_met_count: 127
};

// Demo profiles representing diverse community members
export const DEMO_PROFILES = [
  {
    id: 'profile-001',
    email: 'river@demo.com',
    full_name: 'River Stone',
    username: 'riverstone',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=River',
    bio: 'Flow arts practitioner and water ceremony keeper. Guiding healing journeys through movement and sacred waters.',
    neighborhood: 'Zilker',
    holistic_interests: ['Water Ceremonies', 'Flow Arts', 'Ecstatic Dance', 'Breathwork'],
    verified: true,
    rating: 4.9,
    total_reviews: 78
  },
  {
    id: 'profile-002',
    email: 'cedar@demo.com',
    full_name: 'Cedar Sage',
    username: 'cedarsage',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Cedar',
    bio: 'Indigenous wisdom keeper and sacred plant medicine guide. Bridging ancient traditions with modern healing.',
    neighborhood: 'South Congress',
    holistic_interests: ['Plant Medicine', 'Sweat Lodge', 'Drum Circles', 'Ancestral Healing'],
    verified: true,
    rating: 5.0,
    total_reviews: 92
  },
  {
    id: 'profile-003',
    email: 'rainbow@demo.com',
    full_name: 'Rainbow Moss',
    username: 'rainbowmoss',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rainbow',
    bio: 'Crystal alchemist and energy worker. Harmonizing spaces through sacred geometry and vibrational healing.',
    neighborhood: 'Mueller',
    holistic_interests: ['Crystal Healing', 'Reiki', 'Sacred Geometry', 'Color Therapy'],
    verified: true,
    rating: 4.8,
    total_reviews: 56
  },
  {
    id: 'profile-004',
    email: 'willow@demo.com',
    full_name: 'Willow Moon',
    username: 'willowmoon',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Willow',
    bio: 'Lunar cycle guide and women\'s wisdom keeper. Facilitating sacred circles aligned with nature\'s rhythms.',
    neighborhood: 'Hyde Park',
    holistic_interests: ['Moon Ceremonies', 'Women\'s Circles', 'Herbalism', 'Cycle Wisdom'],
    verified: true,
    rating: 5.0,
    total_reviews: 103
  },
  {
    id: 'profile-005',
    email: 'forest@demo.com',
    full_name: 'Forest Oak',
    username: 'forestoak',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Forest',
    bio: 'Forest therapy guide and earth skills teacher. Reconnecting humanity with the wisdom of trees.',
    neighborhood: 'West Lake Hills',
    holistic_interests: ['Forest Bathing', 'Earth Skills', 'Tree Communication', 'Wild Crafting'],
    verified: true,
    rating: 4.9,
    total_reviews: 84
  },
  {
    id: 'profile-006',
    email: 'meadow@demo.com',
    full_name: 'Meadow Sky',
    username: 'meadowsky',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Meadow',
    bio: 'Breathwork facilitator and somatic healer. Guiding transformation through conscious breathing.',
    neighborhood: 'Crestview',
    holistic_interests: ['Breathwork', 'Somatic Healing', 'Trauma Release', 'Movement Medicine'],
    verified: true,
    rating: 4.8,
    total_reviews: 61
  },
  {
    id: 'profile-007',
    email: 'jasper@demo.com',
    full_name: 'Jasper Rain',
    username: 'jasperrain',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jasper',
    bio: 'Sound journey facilitator and gong master. Creating sonic landscapes for deep meditation.',
    neighborhood: 'Domain',
    holistic_interests: ['Gong Baths', 'Singing Bowls', 'Mantras', 'Vibrational Medicine'],
    verified: true,
    rating: 5.0,
    total_reviews: 97
  },
  {
    id: 'profile-008',
    email: 'sage@demo.com',
    full_name: 'Sage Blossom',
    username: 'sageblossom',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sage',
    bio: 'Ayurvedic practitioner and yoga therapist. Supporting holistic wellness through ancient wisdom.',
    neighborhood: 'East Austin',
    holistic_interests: ['Ayurveda', 'Yoga Therapy', 'Meditation', 'Detox Programs'],
    verified: true,
    rating: 4.9,
    total_reviews: 73
  },
  {
    id: 'profile-009',
    email: 'aurora@demo.com',
    full_name: 'Aurora Dawn',
    username: 'auroradawn',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aurora',
    bio: 'Energy artist and sacred space creator. Painting portals to higher consciousness.',
    neighborhood: 'South Lamar',
    holistic_interests: ['Visionary Art', 'Sacred Space', 'Light Work', 'Creative Healing'],
    verified: true,
    rating: 4.7,
    total_reviews: 45
  }
];

// Demo events showcasing holistic practices and decentralized community activities
export const DEMO_EVENTS = [
  {
    id: 'event-001',
    title: 'Community Sound Bath & Meditation',
    description: 'Join us for a transformative evening of crystal bowl sound healing and guided meditation. We\'ll create a sacred space for deep relaxation and inner peace. All experience levels welcome.',
    created_by: 'profile-003',
    creator_name: 'Rainbow Moss',
    event_type: 'sound_healing',
    status: 'published',
    category: 'wellness',
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days from now
    time: '19:00',
    duration: 90,
    location: 'Harmony Garden Pavilion',
    address: '123 Peace Lane, Willow Creek',
    latitude: 37.7749,
    longitude: -122.4194,
    max_participants: 30,
    current_participants: 18,
    is_free: false,
    price: 20,
    currency: 'Time Credits',
    image_url: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=800',
    tags: ['Sound Healing', 'Meditation', 'Crystal Bowls', 'Relaxation'],
    neighborhood: 'Willow Creek',
    is_virtual: false,
    accessibility_info: 'Wheelchair accessible, mats provided'
  },
  {
    id: 'event-002',
    title: 'Morning Yoga Flow in the Park',
    description: 'Start your day with energizing vinyasa flow yoga surrounded by nature. We\'ll move through sun salutations and standing sequences to awaken body and mind. Bring your own mat.',
    created_by: 'profile-001',
    creator_name: 'River Stone',
    event_type: 'yoga',
    status: 'published',
    category: 'wellness',
    date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(), // Tomorrow
    time: '07:00',
    duration: 60,
    location: 'Riverside Park Meadow',
    address: '456 River Road, Riverside',
    latitude: 37.7849,
    longitude: -122.4094,
    max_participants: 25,
    current_participants: 12,
    is_free: true,
    price: 0,
    currency: 'Free',
    image_url: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800',
    tags: ['Yoga', 'Outdoor', 'Morning Practice', 'Vinyasa'],
    neighborhood: 'Riverside',
    is_virtual: false,
    accessibility_info: 'Flat ground, suitable for all levels'
  },
  {
    id: 'event-003',
    title: 'Permaculture Workshop: Food Forest Design',
    description: 'Learn the principles of permaculture and how to design your own food forest. We\'ll cover companion planting, water harvesting, and creating resilient ecosystems in your backyard.',
    created_by: 'profile-002',
    creator_name: 'Cedar Sage',
    event_type: 'workshop',
    status: 'published',
    category: 'education',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days from now
    time: '14:00',
    duration: 180,
    location: 'Community Garden Center',
    address: '789 Green Way, Oak Valley',
    latitude: 37.7649,
    longitude: -122.4294,
    max_participants: 20,
    current_participants: 15,
    is_free: false,
    price: 35,
    currency: 'Time Credits',
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    tags: ['Permaculture', 'Sustainability', 'Gardening', 'Food Security'],
    neighborhood: 'Oak Valley',
    is_virtual: false,
    accessibility_info: 'Garden paths are gravel, some uneven terrain'
  },
  {
    id: 'event-004',
    title: 'Women\'s New Moon Circle',
    description: 'Gather in sacred sisterhood to honor the new moon. We\'ll share intentions, practice ritual, and support each other\'s journey. A safe space for feminine wisdom and healing.',
    created_by: 'profile-005',
    creator_name: 'Forest Oak',
    event_type: 'ceremony',
    status: 'published',
    category: 'spiritual',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 1 week from now
    time: '19:30',
    duration: 120,
    location: 'Sacred Space Studio',
    address: '321 Moon Street, Garden District',
    latitude: 37.7549,
    longitude: -122.4394,
    max_participants: 12,
    current_participants: 8,
    is_free: false,
    price: 15,
    currency: 'Time Credits',
    image_url: 'https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=800',
    tags: ['Women\'s Circle', 'Moon Ceremony', 'Ritual', 'Sacred Feminine'],
    neighborhood: 'Garden District',
    is_virtual: false,
    accessibility_info: 'Intimate setting, cushions provided'
  },
  {
    id: 'event-005',
    title: 'Tai Chi for Beginners',
    description: 'Discover the gentle power of Tai Chi. Learn basic movements and principles of this ancient practice for balance, flexibility, and inner calm. Perfect for all ages.',
    created_by: 'profile-004',
    creator_name: 'Willow Moon',
    event_type: 'movement',
    status: 'published',
    category: 'wellness',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days from now
    time: '09:00',
    duration: 60,
    location: 'Willow Creek Community Center',
    address: '555 Center Drive, Willow Creek',
    latitude: 37.7749,
    longitude: -122.4094,
    max_participants: 15,
    current_participants: 6,
    is_free: true,
    price: 0,
    currency: 'Free',
    image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800',
    tags: ['Tai Chi', 'Movement', 'Balance', 'Mindfulness'],
    neighborhood: 'Willow Creek',
    is_virtual: false,
    accessibility_info: 'Indoor space, chair options available'
  },
  {
    id: 'event-006',
    title: 'Community Potluck & Skill Share',
    description: 'Bring a dish to share and a skill to teach! This monthly gathering celebrates our diverse talents. Past shares included knitting, fermentation, music, and healing techniques.',
    created_by: 'demo-user-001',
    creator_name: 'Alex Chen',
    event_type: 'gathering',
    status: 'published',
    category: 'community',
    date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), // 4 days from now
    time: '18:00',
    duration: 150,
    location: 'Neighborhood Commons',
    address: '999 Community Lane, Willow Creek',
    latitude: 37.7749,
    longitude: -122.4194,
    max_participants: 50,
    current_participants: 32,
    is_free: true,
    price: 0,
    currency: 'Free',
    image_url: 'https://images.unsplash.com/photo-1540914124281-342587941389?w=800',
    tags: ['Potluck', 'Skill Share', 'Community', 'Networking'],
    neighborhood: 'Willow Creek',
    is_virtual: false,
    accessibility_info: 'Fully accessible venue with ramps'
  },
  {
    id: 'event-007',
    title: 'Virtual Breathwork Journey',
    description: 'Join us online for a powerful breathwork session. Using conscious connected breathing, we\'ll release stored emotions and access expanded states of consciousness.',
    created_by: 'profile-001',
    creator_name: 'River Stone',
    event_type: 'breathwork',
    status: 'published',
    category: 'wellness',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days from now
    time: '20:00',
    duration: 75,
    location: 'Online via Zoom',
    address: 'Virtual Event',
    latitude: null,
    longitude: null,
    max_participants: 100,
    current_participants: 45,
    is_free: false,
    price: 10,
    currency: 'Time Credits',
    image_url: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4a7?w=800',
    tags: ['Breathwork', 'Virtual', 'Healing', 'Consciousness'],
    neighborhood: 'Global',
    is_virtual: true,
    accessibility_info: 'Closed captions available, recording provided'
  },
  {
    id: 'event-008',
    title: 'Herbal Medicine Making Workshop',
    description: 'Learn to make your own herbal tinctures, teas, and salves. We\'ll work with locally sourced plants and discuss their healing properties. Take home your creations!',
    created_by: 'profile-002',
    creator_name: 'Cedar Sage',
    event_type: 'workshop',
    status: 'published',
    category: 'education',
    date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(), // 6 days from now
    time: '13:00',
    duration: 120,
    location: 'The Herb Garden',
    address: '234 Plant Path, Oak Valley',
    latitude: 37.7649,
    longitude: -122.4294,
    max_participants: 12,
    current_participants: 10,
    is_free: false,
    price: 45,
    currency: 'Time Credits',
    image_url: 'https://images.unsplash.com/photo-1509909756405-be0199881695?w=800',
    tags: ['Herbalism', 'DIY', 'Natural Medicine', 'Workshop'],
    neighborhood: 'Oak Valley',
    is_virtual: false,
    accessibility_info: 'Standing workshop, stools available'
  },

  // Austin-specific local events
  {
    id: 'event-009',
    title: 'Barton Springs Full Moon Swim & Ceremony',
    description: 'Join us for a sacred full moon swim at Barton Springs Pool. We\'ll gather for intention setting, take a moonlit swim in the natural spring waters, and close with a gratitude circle.',
    created_by: 'profile-003',
    creator_name: 'Rainbow Moss',
    event_type: 'ceremony',
    status: 'published',
    category: 'spiritual',
    date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    time: '20:00',
    duration: 120,
    location: 'Barton Springs Pool',
    address: '2201 Barton Springs Rd, Austin, TX 78746',
    latitude: 30.2640,
    longitude: -97.7706,
    max_participants: 40,
    current_participants: 28,
    is_free: false,
    price: 15,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1518972559570-7cc1309f3229?w=800',
    tags: ['Full Moon', 'Swimming', 'Ceremony', 'Barton Springs'],
    neighborhood: 'Zilker',
    is_virtual: false,
    accessibility_info: 'Pool has accessible entry, bring towels'
  },
  {
    id: 'event-010',
    title: 'East Austin Community Garden Workday',
    description: 'Help us maintain our community garden! We\'ll be planting seasonal vegetables, building raised beds, and sharing gardening wisdom. Fresh produce goes to local families.',
    created_by: 'profile-002',
    creator_name: 'Cedar Sage',
    event_type: 'gardening',
    status: 'published',
    category: 'community',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    time: '09:00',
    duration: 180,
    location: 'Boggy Creek Community Garden',
    address: '2015 E 12th St, Austin, TX 78702',
    latitude: 30.2712,
    longitude: -97.7281,
    max_participants: 50,
    current_participants: 23,
    is_free: true,
    price: 0,
    currency: 'Free',
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    tags: ['Gardening', 'Community', 'Sustainability', 'East Austin'],
    neighborhood: 'East Austin',
    is_virtual: false,
    accessibility_info: 'Garden paths are wheelchair accessible'
  },
  {
    id: 'event-011',
    title: 'Sunset Ecstatic Dance at Mount Bonnell',
    description: 'Dance freely as the sun sets over Lake Austin! We start with gentle movement, build to ecstatic expression, and end with a silent meditation overlooking the city.',
    created_by: 'profile-005',
    creator_name: 'Forest Oak',
    event_type: 'dance',
    status: 'published',
    category: 'movement',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    time: '18:30',
    duration: 120,
    location: 'Mount Bonnell',
    address: '3800 Mt Bonnell Rd, Austin, TX 78731',
    latitude: 30.3211,
    longitude: -97.7726,
    max_participants: 30,
    current_participants: 19,
    is_free: false,
    price: 25,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=800',
    tags: ['Ecstatic Dance', 'Sunset', 'Mount Bonnell', 'Movement'],
    neighborhood: 'West Austin',
    is_virtual: false,
    accessibility_info: 'Stairs to overlook, alternative viewing area available'
  },
  {
    id: 'event-012',
    title: 'South Congress Farmers Market Meditation',
    description: 'Start your Saturday with a grounding meditation at the SoCo farmers market. We\'ll practice mindful breathing, then explore the market with conscious awareness.',
    created_by: 'profile-004',
    creator_name: 'Willow Moon',
    event_type: 'meditation',
    status: 'published',
    category: 'mindfulness',
    date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    time: '08:00',
    duration: 45,
    location: 'SoCo Farmers Market',
    address: '1826 S Congress Ave, Austin, TX 78704',
    latitude: 30.2481,
    longitude: -97.7494,
    max_participants: 20,
    current_participants: 14,
    is_free: true,
    price: 0,
    currency: 'Free',
    image_url: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800',
    tags: ['Meditation', 'Farmers Market', 'South Congress', 'Mindfulness'],
    neighborhood: 'South Congress',
    is_virtual: false,
    accessibility_info: 'Flat terrain, shaded area available'
  },
  {
    id: 'event-013',
    title: 'Greenbelt Nature Therapy Walk',
    description: 'Experience the healing power of nature with a guided forest bathing walk through the Greenbelt. We\'ll practice mindful observation, tree meditation, and creek-side reflection.',
    created_by: 'profile-001',
    creator_name: 'River Stone',
    event_type: 'nature_therapy',
    status: 'published',
    category: 'wellness',
    date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    time: '10:00',
    duration: 150,
    location: 'Barton Creek Greenbelt',
    address: '3755 S Capital of Texas Hwy, Austin, TX 78704',
    latitude: 30.2459,
    longitude: -97.8081,
    max_participants: 15,
    current_participants: 11,
    is_free: false,
    price: 30,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    tags: ['Forest Bathing', 'Nature Therapy', 'Greenbelt', 'Hiking'],
    neighborhood: 'Barton Hills',
    is_virtual: false,
    accessibility_info: 'Moderate trail, not wheelchair accessible'
  },
  {
    id: 'event-014',
    title: 'Mueller Lake Park Tai Chi',
    description: 'Join our weekly Tai Chi practice at Mueller Lake Park. We practice the 24-form Yang style, perfect for beginners and experienced practitioners alike.',
    created_by: 'profile-004',
    creator_name: 'Willow Moon',
    event_type: 'tai_chi',
    status: 'published',
    category: 'movement',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    time: '07:30',
    duration: 60,
    location: 'Mueller Lake Park',
    address: '4550 Mueller Blvd, Austin, TX 78723',
    latitude: 30.2969,
    longitude: -97.7055,
    max_participants: 35,
    current_participants: 22,
    is_free: true,
    price: 0,
    currency: 'Free',
    image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800',
    tags: ['Tai Chi', 'Mueller', 'Morning Practice', 'Qigong'],
    neighborhood: 'Mueller',
    is_virtual: false,
    accessibility_info: 'Flat surface, wheelchair accessible'
  },
  {
    id: 'event-015',
    title: 'Lady Bird Lake SUP Yoga',
    description: 'Practice yoga on a stand-up paddleboard! We\'ll start with basic SUP skills, then flow through gentle yoga poses while floating on Lady Bird Lake.',
    created_by: 'profile-001',
    creator_name: 'River Stone',
    event_type: 'yoga',
    status: 'published',
    category: 'movement',
    date: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    time: '17:00',
    duration: 90,
    location: 'Texas Rowing Center',
    address: '1541 W Cesar Chavez St, Austin, TX 78703',
    latitude: 30.2747,
    longitude: -97.7628,
    max_participants: 12,
    current_participants: 10,
    is_free: false,
    price: 45,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
    tags: ['SUP Yoga', 'Lady Bird Lake', 'Water Yoga', 'Paddleboard'],
    neighborhood: 'Downtown',
    is_virtual: false,
    accessibility_info: 'Must be able to swim, life jackets provided'
  },
  {
    id: 'event-016',
    title: 'Crestview Community Potluck & Song Circle',
    description: 'Bring a dish to share and your voice! We\'ll enjoy a community meal followed by an acoustic song circle. All instruments and skill levels welcome.',
    created_by: 'profile-002',
    creator_name: 'Cedar Sage',
    event_type: 'gathering',
    status: 'published',
    category: 'community',
    date: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(),
    time: '18:00',
    duration: 180,
    location: 'Brentwood Park',
    address: '6710 Arroyo Seco, Austin, TX 78757',
    latitude: 30.3378,
    longitude: -97.7311,
    max_participants: 60,
    current_participants: 34,
    is_free: true,
    price: 0,
    currency: 'Bring a dish',
    image_url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800',
    tags: ['Potluck', 'Music', 'Community', 'Crestview'],
    neighborhood: 'Crestview',
    is_virtual: false,
    accessibility_info: 'Park pavilion is wheelchair accessible'
  },
  {
    id: 'event-017',
    title: 'Domain Northside Crystal Bowl Healing',
    description: 'Experience deep relaxation with crystal singing bowls at the Domain. We\'ll create a sonic sanctuary for stress release and energetic alignment.',
    created_by: 'profile-003',
    creator_name: 'Rainbow Moss',
    event_type: 'sound_healing',
    status: 'published',
    category: 'wellness',
    date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    time: '19:30',
    duration: 75,
    location: 'Domain NORTHSIDE Park',
    address: '11410 Century Oaks Terrace, Austin, TX 78758',
    latitude: 30.3958,
    longitude: -97.7238,
    max_participants: 25,
    current_participants: 18,
    is_free: false,
    price: 35,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=800',
    tags: ['Crystal Bowls', 'Sound Healing', 'Domain', 'Meditation'],
    neighborhood: 'Domain',
    is_virtual: false,
    accessibility_info: 'Indoor venue, elevator access available'
  },
  {
    id: 'event-018',
    title: 'Zilker Botanical Garden Mindful Photography',
    description: 'Explore the beauty of Zilker Botanical Garden through mindful photography. Learn to see with fresh eyes and capture the essence of nature\'s patterns.',
    created_by: 'profile-005',
    creator_name: 'Forest Oak',
    event_type: 'workshop',
    status: 'published',
    category: 'creative',
    date: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000).toISOString(),
    time: '09:00',
    duration: 120,
    location: 'Zilker Botanical Garden',
    address: '2220 Barton Springs Rd, Austin, TX 78746',
    latitude: 30.2689,
    longitude: -97.7723,
    max_participants: 15,
    current_participants: 12,
    is_free: false,
    price: 40,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=800',
    tags: ['Photography', 'Mindfulness', 'Zilker', 'Nature'],
    neighborhood: 'Zilker',
    is_virtual: false,
    accessibility_info: 'Paved paths throughout garden'
  },
  {
    id: 'event-019',
    title: 'Hyde Park Fire Ceremony & Storytelling',
    description: 'Gather around the sacred fire for an evening of storytelling and release. Bring something to symbolically release into the fire and a story to share.',
    created_by: 'profile-002',
    creator_name: 'Cedar Sage',
    event_type: 'ceremony',
    status: 'published',
    category: 'spiritual',
    date: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    time: '19:00',
    duration: 150,
    location: 'Private Garden Hyde Park',
    address: '4400 Ave B, Austin, TX 78751',
    latitude: 30.3074,
    longitude: -97.7335,
    max_participants: 20,
    current_participants: 16,
    is_free: false,
    price: 20,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800',
    tags: ['Fire Ceremony', 'Storytelling', 'Hyde Park', 'Ritual'],
    neighborhood: 'Hyde Park',
    is_virtual: false,
    accessibility_info: 'Backyard setting, some uneven ground'
  },
  {
    id: 'event-020',
    title: 'Rainey Street Sunrise Breathwork',
    description: 'Start your day with powerful breathwork overlooking Lady Bird Lake from Rainey Street. We\'ll practice pranayama techniques for energy and clarity.',
    created_by: 'profile-004',
    creator_name: 'Willow Moon',
    event_type: 'breathwork',
    status: 'published',
    category: 'wellness',
    date: new Date(Date.now() + 13 * 24 * 60 * 60 * 1000).toISOString(),
    time: '06:30',
    duration: 60,
    location: 'Rainey Street District',
    address: '295 Rainey St, Austin, TX 78701',
    latitude: 30.2587,
    longitude: -97.7390,
    max_participants: 25,
    current_participants: 17,
    is_free: true,
    price: 0,
    currency: 'Donation-based',
    image_url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    tags: ['Breathwork', 'Sunrise', 'Rainey Street', 'Pranayama'],
    neighborhood: 'Rainey District',
    is_virtual: false,
    accessibility_info: 'Rooftop location with elevator access'
  },
  {
    id: 'event-021',
    title: 'Plant Medicine Integration Circle',
    description: 'A safe space to share and integrate plant medicine experiences. We\'ll explore insights, offer support, and practice embodiment exercises together.',
    created_by: 'profile-002',
    creator_name: 'Cedar Sage',
    event_type: 'integration_circle',
    status: 'published',
    category: 'spiritual',
    date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    time: '18:30',
    duration: 120,
    location: 'Sacred Space Studio',
    address: '1200 E 6th St, Austin, TX 78702',
    latitude: 30.2621,
    longitude: -97.7250,
    max_participants: 12,
    current_participants: 9,
    is_free: false,
    price: 30,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800',
    tags: ['Integration', 'Plant Medicine', 'Sacred Circle', 'Support'],
    neighborhood: 'East Austin',
    is_virtual: false,
    accessibility_info: 'Ground floor, wheelchair accessible'
  },
  {
    id: 'event-022',
    title: 'Goddess Embodiment Dance',
    description: 'Awaken your divine feminine through sacred movement and dance. All genders welcome to explore the goddess energy within.',
    created_by: 'profile-001',
    creator_name: 'River Stone',
    event_type: 'dance',
    status: 'published',
    category: 'movement',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    time: '19:00',
    duration: 90,
    location: 'Movement Medicine Studio',
    address: '2700 W Anderson Ln, Austin, TX 78757',
    latitude: 30.3583,
    longitude: -97.7356,
    max_participants: 20,
    current_participants: 16,
    is_free: false,
    price: 25,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800',
    tags: ['Sacred Dance', 'Goddess Energy', 'Embodiment', 'Movement'],
    neighborhood: 'Crestview',
    is_virtual: false,
    accessibility_info: 'Spacious studio, all abilities welcome'
  },
  {
    id: 'event-023',
    title: 'Ancestral Healing & Family Constellations',
    description: 'Explore and heal family patterns through constellation work. Witness or represent in this powerful group healing modality.',
    created_by: 'profile-008',
    creator_name: 'Sage Blossom',
    event_type: 'healing_circle',
    status: 'published',
    category: 'healing',
    date: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    time: '14:00',
    duration: 180,
    location: 'Unity Church Austin',
    address: '5501 W US-290, Austin, TX 78735',
    latitude: 30.2367,
    longitude: -97.8569,
    max_participants: 30,
    current_participants: 22,
    is_free: false,
    price: 45,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1516589091380-5d8e87df6999?w=800',
    tags: ['Family Constellations', 'Ancestral Healing', 'Trauma Release'],
    neighborhood: 'West Lake Hills',
    is_virtual: false,
    accessibility_info: 'Wheelchair accessible, chairs provided'
  },
  {
    id: 'event-024',
    title: 'Kids Garden Magic Hour',
    description: 'Bring your little ones to explore the magic of gardening! We\'ll plant seeds, meet garden creatures, and share healthy snacks.',
    created_by: 'demo-user-001',
    creator_name: 'Sunflower Lily',
    event_type: 'family_event',
    status: 'published',
    category: 'education',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    time: '10:00',
    duration: 60,
    location: 'Springdale Farm',
    address: '755 Springdale Rd, Austin, TX 78702',
    latitude: 30.2615,
    longitude: -97.6989,
    max_participants: 15,
    current_participants: 11,
    is_free: true,
    price: 0,
    currency: 'Free',
    image_url: 'https://images.unsplash.com/photo-1523348837708-15d4a09e3386?w=800',
    tags: ['Kids', 'Garden', 'Education', 'Family'],
    neighborhood: 'East Austin',
    is_virtual: false,
    accessibility_info: 'Stroller friendly, shaded areas'
  },
  {
    id: 'event-025',
    title: 'Sacred Cacao & Heart Opening Ceremony',
    description: 'Journey with ceremonial cacao to open your heart and connect with your inner wisdom. Live music and guided meditation included.',
    created_by: 'profile-007',
    creator_name: 'Jasper Rain',
    event_type: 'ceremony',
    status: 'published',
    category: 'spiritual',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    time: '18:00',
    duration: 150,
    location: 'The Sanctuary ATX',
    address: '3914 N Lamar Blvd, Austin, TX 78756',
    latitude: 30.3089,
    longitude: -97.7418,
    max_participants: 25,
    current_participants: 20,
    is_free: false,
    price: 40,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1617634667039-8e4cb277ab46?w=800',
    tags: ['Cacao Ceremony', 'Heart Opening', 'Live Music', 'Sacred'],
    neighborhood: 'Hyde Park',
    is_virtual: false,
    accessibility_info: 'Ground level access, cushions and chairs available'
  },
  {
    id: 'event-026',
    title: 'Men\'s Sacred Fire Circle',
    description: 'A gathering for men to share, support, and strengthen each other around the sacred fire. Drumming, storytelling, and brotherhood.',
    created_by: 'profile-005',
    creator_name: 'Forest Oak',
    event_type: 'mens_circle',
    status: 'published',
    category: 'community',
    date: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(),
    time: '19:30',
    duration: 120,
    location: 'Private Land West Austin',
    address: '12400 Bee Cave Rd, Austin, TX 78738',
    latitude: 30.3073,
    longitude: -97.9320,
    max_participants: 20,
    current_participants: 14,
    is_free: false,
    price: 15,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800',
    tags: ['Men\'s Circle', 'Fire Ceremony', 'Brotherhood', 'Sacred Masculine'],
    neighborhood: 'West Lake Hills',
    is_virtual: false,
    accessibility_info: 'Outdoor terrain, bring camping chair'
  },
  {
    id: 'event-027',
    title: 'Community Herb Walk & Medicine Making',
    description: 'Learn to identify local medicinal plants and create your own herbal remedies. We\'ll make tinctures and salves to take home.',
    created_by: 'profile-004',
    creator_name: 'Willow Moon',
    event_type: 'workshop',
    status: 'published',
    category: 'education',
    date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    time: '09:00',
    duration: 180,
    location: 'Wild Basin Wilderness',
    address: '805 N Capital of Texas Hwy, Austin, TX 78746',
    latitude: 30.3108,
    longitude: -97.8249,
    max_participants: 12,
    current_participants: 10,
    is_free: false,
    price: 35,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=800',
    tags: ['Herbalism', 'Plant Medicine', 'Nature Walk', 'DIY'],
    neighborhood: 'West Lake Hills',
    is_virtual: false,
    accessibility_info: 'Trail walking required, moderate difficulty'
  },
  {
    id: 'event-028',
    title: 'Quantum Healing & Light Language Activation',
    description: 'Experience quantum healing frequencies and light language transmissions for cellular activation and spiritual awakening.',
    created_by: 'profile-003',
    creator_name: 'Rainbow Moss',
    event_type: 'energy_healing',
    status: 'published',
    category: 'healing',
    date: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000).toISOString(),
    time: '19:00',
    duration: 90,
    location: 'Crystal Works',
    address: '908 W 12th St, Austin, TX 78703',
    latitude: 30.2764,
    longitude: -97.7526,
    max_participants: 18,
    current_participants: 15,
    is_free: false,
    price: 50,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1568063386229-0978db43613f?w=800',
    tags: ['Quantum Healing', 'Light Language', 'Energy Work', 'Activation'],
    neighborhood: 'West Austin',
    is_virtual: false,
    accessibility_info: 'Fully accessible, mats provided'
  },
  {
    id: 'event-029',
    title: 'Grief & Grace: Community Support Circle',
    description: 'A compassionate space to process grief and loss together. We\'ll share, witness, and support each other through life\'s transitions.',
    created_by: 'profile-006',
    creator_name: 'Meadow Sky',
    event_type: 'support_circle',
    status: 'published',
    category: 'healing',
    date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    time: '18:30',
    duration: 90,
    location: 'Austin Mindfulness Center',
    address: '1803 W 35th St, Austin, TX 78703',
    latitude: 30.3057,
    longitude: -97.7576,
    max_participants: 15,
    current_participants: 8,
    is_free: true,
    price: 0,
    currency: 'Donation-based',
    image_url: 'https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=800',
    tags: ['Grief Support', 'Community', 'Healing', 'Compassion'],
    neighborhood: 'Bryker Woods',
    is_virtual: false,
    accessibility_info: 'Wheelchair accessible, quiet space'
  },
  {
    id: 'event-030',
    title: 'Art as Medicine: Intuitive Painting Journey',
    description: 'No experience needed! Release your inner artist and let intuition guide your brush. A healing journey through color and creativity.',
    created_by: 'profile-009',
    creator_name: 'Aurora Dawn',
    event_type: 'art_therapy',
    status: 'published',
    category: 'creative',
    date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    time: '14:00',
    duration: 120,
    location: 'Art Garage Austin',
    address: '2324 S Lamar Blvd, Austin, TX 78704',
    latitude: 30.2471,
    longitude: -97.7825,
    max_participants: 16,
    current_participants: 13,
    is_free: false,
    price: 45,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800',
    tags: ['Art Therapy', 'Intuitive Art', 'Creative Healing', 'Self-Expression'],
    neighborhood: 'South Lamar',
    is_virtual: false,
    accessibility_info: 'Wheelchair accessible, all materials provided'
  }
];

// Demo spaces for community sharing
export const DEMO_SPACES = [
  {
    id: 'space-001',
    slug: 'springdale-farm-community-pavilion',
    name: 'Springdale Farm Community Pavilion',
    description: 'Historic urban farm pavilion surrounded by organic gardens. Perfect for farm-to-table dinners, workshops, and healing ceremonies. This beautiful 1920s pavilion has hosted countless community gatherings and features exposed beam ceilings, natural wood floors, and panoramic views of our organic gardens.',
    type: 'outdoor_pavilion',
    capacity: 30,
    address: '755 Springdale Rd, Austin, TX 78702',
    neighborhood: 'East Austin',
    amenities: [
      { amenity: 'Electricity' },
      { amenity: 'Restrooms' },
      { amenity: 'Garden Access' },
      { amenity: 'Sound System' },
      { amenity: 'WiFi' },
      { amenity: 'Kitchen Access' },
      { amenity: 'Tables & Chairs' }
    ],
    availability: 'Weekends and evenings',
    is_free: false,
    price_per_hour: 25,
    currency: 'Time Credits',
    donation_suggested: '25 Time Credits per hour or sliding scale',
    created_by: 'profile-003',
    host_name: 'Rainbow Moss',
    owner: {
      full_name: 'Rainbow Moss',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rainbow',
      verified: true
    },
    image_urls: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=800'
    ],
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    guidelines: 'Please respect the land and leave no trace. Set up and clean up time is included in your booking. Composting and recycling stations are available. No amplified music after 9pm on weeknights. We encourage sustainable practices and ask that you minimize single-use items.',
    accessibility_features: [
      { feature: 'Wheelchair accessible pathways' },
      { feature: 'Accessible restroom' },
      { feature: 'Level ground surfaces' },
      { feature: 'Designated parking' }
    ],
    animals_allowed: true,
    animal_types: [
      { animal_type: 'dogs' },
      { animal_type: 'cats' }
    ],
    owner_has_pets: false,
    holistic_categories: [
      { category: 'Farm-to-Table Events' },
      { category: 'Permaculture Workshops' },
      { category: 'Sound Healing' },
      { category: 'Community Gatherings' },
      { category: 'Herbalism Classes' }
    ],
    list_publicly: true,
    status: 'available',
    verified: true,
    rating: 4.9,
    total_bookings: 156
  },
  {
    id: 'space-002',
    slug: 'casa-de-luz-healing-studio',
    name: 'Casa de Luz Healing Studio',
    description: 'Intimate studio at Casa de Luz wellness center designed for healing work, small circles, and spiritual practices. This serene space features beautiful natural lighting, handcrafted altar with crystals and sacred objects, bamboo floors, and energy-clearing performed between each use. The studio maintains a peaceful vibration perfect for deep healing work.',
    type: 'studio',
    capacity: 12,
    address: '1701 Toomey Rd, Austin, TX 78704',
    neighborhood: 'South Congress',
    amenities: [
      { amenity: 'Yoga Props & Mats' },
      { amenity: 'Sound Healing Instruments' },
      { amenity: 'Sacred Altar Space' },
      { amenity: 'Tea Kitchen' },
      { amenity: 'Essential Oil Diffuser' },
      { amenity: 'Meditation Cushions' },
      { amenity: 'Blankets & Bolsters' }
    ],
    availability: 'Daily 8am-9pm',
    is_free: false,
    price_per_hour: 15,
    currency: 'Time Credits',
    donation_suggested: '15 Time Credits per hour or energy exchange',
    created_by: 'profile-005',
    host_name: 'Forest Oak',
    owner: {
      full_name: 'Forest Oak',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Forest',
      verified: true
    },
    image_urls: [
      'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800',
      'https://images.unsplash.com/photo-1600618528240-fb9fc964b853?w=800'
    ],
    image_url: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800',
    guidelines: 'Please maintain sacred silence in common areas. Remove shoes before entering. Light cleansing incense or sage is welcome. Please arrive 10 minutes early to settle in. We ask that you help maintain the peaceful energy of the space.',
    accessibility_features: [
      { feature: 'Ground floor location' },
      { feature: 'Wide doorways' },
      { feature: 'Accessible restroom nearby' }
    ],
    animals_allowed: false,
    owner_has_pets: true,
    owner_pet_types: ['Therapy Cat'],
    holistic_categories: [
      { category: 'Reiki & Energy Work' },
      { category: 'Sound Healing' },
      { category: 'Meditation Circles' },
      { category: 'Breathwork' },
      { category: 'Sacred Ceremonies' }
    ],
    list_publicly: true,
    status: 'available',
    verified: true,
    rating: 5.0,
    total_bookings: 89
  },
  {
    id: 'space-003',
    slug: 'mueller-community-garden-greenhouse',
    name: 'Mueller Community Garden Greenhouse',
    description: 'Year-round growing space with workshop area in the sustainable Mueller development. This solar-powered greenhouse features raised beds, potting stations, seed library, and demonstration gardens. Perfect for teaching permaculture, herbalism, and sustainable living practices. The space includes rainwater harvesting systems and composting demonstrations.',
    type: 'greenhouse',
    capacity: 20,
    address: '4550 Mueller Blvd, Austin, TX 78723',
    neighborhood: 'Mueller',
    amenities: [
      { amenity: 'Water Access & Hoses' },
      { amenity: 'Garden Tools Library' },
      { amenity: 'Workshop Seating' },
      { amenity: 'Teaching Whiteboard' },
      { amenity: 'Seed Starting Station' },
      { amenity: 'Compost Bins' },
      { amenity: 'Shade Cloth Areas' }
    ],
    availability: 'Weekdays and Saturday mornings',
    is_free: true,
    price_per_hour: 0,
    currency: 'Free',
    donation_suggested: 'Volunteer hours or plant donations welcome',
    created_by: 'profile-002',
    host_name: 'Cedar Sage',
    owner: {
      full_name: 'Cedar Sage',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Cedar',
      verified: true
    },
    image_urls: [
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
      'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800'
    ],
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    guidelines: 'This is a chemical-free space - only organic practices allowed. Please return tools clean and in their designated spots. Water conservation is important - use drip irrigation when possible. Children must be supervised at all times. Take only what you need from the harvest share.',
    accessibility_features: [
      { feature: 'Wide pathways between beds' },
      { feature: 'Raised beds at various heights' },
      { feature: 'Wheelchair accessible entrance' },
      { feature: 'Accessible tool storage' }
    ],
    animals_allowed: true,
    animal_types: [
      { animal_type: 'dogs' }
    ],
    owner_has_pets: false,
    holistic_categories: [
      { category: 'Permaculture Classes' },
      { category: 'Herbalism Workshops' },
      { category: 'Seed Saving' },
      { category: 'Composting Education' },
      { category: 'Children\'s Garden Programs' }
    ],
    list_publicly: true,
    status: 'available',
    verified: true,
    rating: 4.7,
    total_bookings: 234
  },
  {
    id: 'space-004',
    slug: 'zilker-botanical-garden-pavilion',
    name: 'Zilker Botanical Garden Pavilion',
    description: 'Beautiful garden venue within Zilker Park featuring native Texas plants and peaceful meditation spaces. Surrounded by butterfly gardens, herb spirals, and a tranquil koi pond. The covered pavilion offers shade while maintaining connection to nature. Perfect for ceremonies, workshops, and mindful gatherings.',
    type: 'garden_pavilion',
    capacity: 40,
    address: '2220 Barton Springs Rd, Austin, TX 78746',
    neighborhood: 'Zilker',
    amenities: [
      { amenity: 'Garden Access' },
      { amenity: 'Covered Pavilion' },
      { amenity: 'Water Features' },
      { amenity: 'Restrooms' },
      { amenity: 'Picnic Tables' },
      { amenity: 'Nature Trails' },
      { amenity: 'Meditation Benches' }
    ],
    availability: 'Daily with reservation',
    is_free: false,
    price_per_hour: 20,
    currency: 'Time Credits',
    donation_suggested: '20 Time Credits per hour or plant donations',
    created_by: 'profile-004',
    host_name: 'Willow Moon',
    owner: {
      full_name: 'Willow Moon',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Willow',
      verified: true
    },
    image_urls: [
      'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
      'https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=800'
    ],
    image_url: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
    guidelines: 'Please respect all plant life - stay on marked paths. No picking flowers or disturbing wildlife. Quiet hours after sunset. Leave no trace principles apply. Consider the sacred nature of this space in your activities.',
    accessibility_features: [
      { feature: 'Paved pathways' },
      { feature: 'Accessible parking nearby' },
      { feature: 'Ramps to pavilion' },
      { feature: 'Accessible restrooms' }
    ],
    animals_allowed: true,
    animal_types: [
      { animal_type: 'dogs' },
      { animal_type: 'small_pets' }
    ],
    owner_has_pets: false,
    holistic_categories: [
      { category: 'Garden Ceremonies' },
      { category: 'Nature Meditation' },
      { category: 'Herbalism Classes' },
      { category: 'Moon Circles' },
      { category: 'Earth-Based Rituals' }
    ],
    list_publicly: true,
    status: 'available',
    verified: true,
    rating: 4.9,
    total_bookings: 167
  },
  {
    id: 'space-005',
    slug: 'hyde-park-community-center',
    name: 'Hyde Park Community Center',
    description: 'Historic 1930s community center with original hardwood floors and vintage charm. Features multiple meeting rooms, a full commercial kitchen, and a beautiful tree-shaded courtyard with string lights. This beloved neighborhood hub has hosted countless potlucks, workshops, and celebrations. The space embodies community spirit and mutual aid.',
    type: 'community_center',
    capacity: 60,
    address: '4102 Ave G, Austin, TX 78751',
    neighborhood: 'Hyde Park',
    amenities: [
      { amenity: 'Multiple Meeting Rooms' },
      { amenity: 'Commercial Kitchen' },
      { amenity: 'Shaded Courtyard' },
      { amenity: 'AV Equipment' },
      { amenity: 'Free Parking' },
      { amenity: 'WiFi' },
      { amenity: 'Stage Area' },
      { amenity: 'Piano' }
    ],
    availability: 'All week',
    is_free: true,
    price_per_hour: 0,
    currency: 'Community Service',
    donation_suggested: 'Volunteer hours or community service appreciated',
    created_by: 'profile-006',
    host_name: 'Meadow Sky',
    owner: {
      full_name: 'Meadow Sky',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Meadow',
      verified: true
    },
    image_urls: [
      'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'
    ],
    image_url: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
    guidelines: 'This is a community-supported space - please help with setup and cleanup. Kitchen use requires food handler certification. Respect quiet hours after 10pm. We operate on gift economy principles - take what you need, give what you can.',
    accessibility_features: [
      { feature: 'Full wheelchair accessibility' },
      { feature: 'Automatic doors' },
      { feature: 'Accessible restrooms' },
      { feature: 'Hearing loop system' },
      { feature: 'Large print materials available' }
    ],
    animals_allowed: true,
    animal_types: [
      { animal_type: 'dogs' },
      { animal_type: 'cats' }
    ],
    owner_has_pets: false,
    holistic_categories: [
      { category: 'Community Potlucks' },
      { category: 'Skill Shares' },
      { category: 'Support Groups' },
      { category: 'Movement Classes' },
      { category: 'Neighborhood Meetings' }
    ],
    list_publicly: true,
    status: 'available',
    verified: true,
    rating: 4.8,
    total_bookings: 312
  },
  {
    id: 'space-006',
    slug: 'crestview-urban-farm',
    name: 'Crestview Urban Farm',
    description: 'Working 2-acre urban farm with teaching pavilion, food forest, and demonstration gardens. Features aquaponics systems, chicken coops, bee hives, and seasonal vegetable production. Our mission is teaching sustainable living and building food security. Monthly harvest shares available for regular users.',
    type: 'urban_farm',
    capacity: 35,
    address: '7601 N Lamar Blvd, Austin, TX 78752',
    neighborhood: 'Crestview',
    amenities: [
      { amenity: 'Teaching Pavilion' },
      { amenity: 'Tool Library' },
      { amenity: 'Composting Systems' },
      { amenity: 'Garden Beds' },
      { amenity: 'Greenhouse' },
      { amenity: 'Rainwater Collection' },
      { amenity: 'Solar Power' }
    ],
    availability: 'Weekends and evenings',
    is_free: false,
    price_per_hour: 15,
    currency: 'Time Credits',
    donation_suggested: '15 Time Credits or work trade',
    created_by: 'profile-007',
    host_name: 'Jasper Rain',
    owner: {
      full_name: 'Jasper Rain',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jasper',
      verified: true
    },
    image_urls: [
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
      'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800'
    ],
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    guidelines: 'This is a working farm - please respect crops and livestock. Children must be supervised around animals. Closed-toe shoes required. We practice regenerative agriculture - no chemicals. Help yourself to herbs from the community spiral garden.',
    accessibility_features: [
      { feature: 'Gravel pathways' },
      { feature: 'Accessible pavilion' },
      { feature: 'Raised beds at varying heights' }
    ],
    animals_allowed: true,
    animal_types: [
      { animal_type: 'dogs' }
    ],
    owner_has_pets: true,
    owner_pet_types: ['Farm Animals', 'Chickens', 'Goats'],
    holistic_categories: [
      { category: 'Permaculture Design' },
      { category: 'Farm-to-Table Cooking' },
      { category: 'Beekeeping' },
      { category: 'Composting Workshops' },
      { category: 'Seed Saving' }
    ],
    list_publicly: true,
    status: 'available',
    verified: true,
    rating: 5.0,
    total_bookings: 189
  },
  {
    id: 'space-007',
    slug: 'domain-northside-rooftop-garden',
    name: 'Domain NORTHSIDE Rooftop Garden',
    description: 'Modern 5th floor rooftop garden with panoramic city views and raised garden beds growing herbs and vegetables. Features shade sails, misting system, and comfortable seating areas. The sunset views are spectacular, making it perfect for evening meditation, rooftop yoga, or stargazing gatherings.',
    type: 'rooftop_garden',
    capacity: 45,
    address: '11410 Century Oaks Terrace, Austin, TX 78758',
    neighborhood: 'Domain',
    amenities: [
      { amenity: '360° City Views' },
      { amenity: 'Organic Garden Beds' },
      { amenity: 'Shade Structures' },
      { amenity: 'Elevator Access' },
      { amenity: 'LED String Lights' },
      { amenity: 'Misting System' },
      { amenity: 'Yoga Deck' }
    ],
    availability: 'Daily 7am-9pm',
    is_free: false,
    price_per_hour: 25,
    currency: 'Time Credits',
    donation_suggested: '25 Time Credits or sliding scale',
    created_by: 'profile-008',
    host_name: 'Sage Blossom',
    owner: {
      full_name: 'Sage Blossom',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sage',
      verified: true
    },
    image_urls: [
      'https://images.unsplash.com/photo-1600618528240-fb9fc964b853?w=800',
      'https://images.unsplash.com/photo-1506184155123-73f3f63c4527?w=800'
    ],
    image_url: 'https://images.unsplash.com/photo-1600618528240-fb9fc964b853?w=800',
    guidelines: 'Wind can be strong - secure all items. No glass containers. Quiet hours after 9pm to respect residents below. Please water the garden beds if you use herbs. Best sunrise views are from the east corner.',
    accessibility_features: [
      { feature: 'Elevator to rooftop' },
      { feature: 'Level surfaces' },
      { feature: 'Accessible seating areas' },
      { feature: 'Wide pathways' }
    ],
    animals_allowed: false,
    owner_has_pets: false,
    holistic_categories: [
      { category: 'Sunrise/Sunset Yoga' },
      { category: 'Meditation Groups' },
      { category: 'Stargazing Circles' },
      { category: 'Urban Gardening' },
      { category: 'Breathwork Sessions' }
    ],
    list_publicly: true,
    status: 'available',
    verified: true,
    rating: 4.7,
    total_bookings: 145
  },
  {
    id: 'space-008',
    slug: 'west-lake-hills-forest-sanctuary',
    name: 'West Lake Hills Forest Sanctuary',
    description: 'Private 5-acre forest retreat with ancient oak groves, meditation platforms built around trees, stone labyrinth, and ceremonial fire circle with hill country views. This sacred land has been tended with love for decades. Features natural spring, crystal grid, and multiple quiet spaces for solitary practice.',
    type: 'forest_sanctuary',
    capacity: 25,
    address: '3800 Bee Cave Rd, West Lake Hills, TX 78746',
    neighborhood: 'West Lake Hills',
    amenities: [
      { amenity: 'Sacred Fire Circle' },
      { amenity: 'Stone Labyrinth' },
      { amenity: 'Tree Platforms' },
      { amenity: 'Nature Trails' },
      { amenity: 'Natural Spring' },
      { amenity: 'Medicine Wheel' },
      { amenity: 'Camping Areas' }
    ],
    availability: 'By special arrangement',
    is_free: false,
    price_per_hour: 35,
    currency: 'Time Credits',
    donation_suggested: '35 Time Credits or sacred reciprocity',
    created_by: 'profile-009',
    host_name: 'Aurora Dawn',
    owner: {
      full_name: 'Aurora Dawn',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aurora',
      verified: true
    },
    image_urls: [
      'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=800',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800'
    ],
    image_url: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=800',
    guidelines: 'This is sacred land - please enter with reverence. Leave all offerings biodegradable. Fire circle requires fire tender certification. No drugs or alcohol. Take only pictures, leave only footprints. The land speaks to those who listen.',
    accessibility_features: [
      { feature: 'Some accessible trails' },
      { feature: 'Accessible parking area' },
      { feature: 'Natural terrain - limited accessibility' }
    ],
    animals_allowed: true,
    animal_types: [
      { animal_type: 'dogs' },
      { animal_type: 'cats' }
    ],
    owner_has_pets: true,
    owner_pet_types: ['Rescue Dogs'],
    holistic_categories: [
      { category: 'Vision Quests' },
      { category: 'Fire Ceremonies' },
      { category: 'Forest Bathing' },
      { category: 'Sacred Rituals' },
      { category: 'Silent Retreats' }
    ],
    list_publicly: false,
    status: 'available',
    verified: true,
    rating: 5.0,
    total_bookings: 98
  }
];

// Demo neighborhoods representing Austin communities
export const DEMO_NEIGHBORHOODS = [
  {
    id: 'hood-001',
    name: 'East Austin',
    slug: 'east-austin',
    description: 'Vibrant creative community known for urban farming, art studios, and community gardens. Strong focus on sustainability and local food systems.',
    member_count: 456,
    event_count: 42,
    coordinator: 'Cedar Sage',
    values: ['Community Gardens', 'Art & Culture', 'Sustainability', 'Local Food'],
    is_active: true
  },
  {
    id: 'hood-002',
    name: 'South Congress',
    slug: 'south-congress',
    description: 'Eclectic neighborhood blending wellness studios, farmers markets, and conscious businesses. Home to many holistic practitioners.',
    member_count: 389,
    event_count: 38,
    coordinator: 'River Stone',
    values: ['Wellness', 'Local Business', 'Mindfulness', 'Creative Expression'],
    is_active: true
  },
  {
    id: 'hood-003',
    name: 'Zilker',
    slug: 'zilker',
    description: 'Nature-centered community near Barton Springs and the Greenbelt. Focus on outdoor wellness, environmental protection, and sacred ceremonies.',
    member_count: 412,
    event_count: 35,
    coordinator: 'Rainbow Moss',
    values: ['Nature Connection', 'Sacred Water', 'Environmental Care', 'Outdoor Wellness'],
    is_active: true
  },
  {
    id: 'hood-004',
    name: 'Mueller',
    slug: 'mueller',
    description: 'Modern sustainable community with parks, community gardens, and wellness spaces. Emphasis on green living and mindful development.',
    member_count: 298,
    event_count: 26,
    coordinator: 'Willow Moon',
    values: ['Sustainable Living', 'Community Health', 'Green Spaces', 'Innovation'],
    is_active: true
  },
  {
    id: 'hood-005',
    name: 'Hyde Park',
    slug: 'hyde-park',
    description: 'Historic neighborhood with strong community bonds, home gatherings, and storytelling traditions. Focus on intergenerational wisdom.',
    member_count: 234,
    event_count: 22,
    coordinator: 'Forest Oak',
    values: ['Community Wisdom', 'Storytelling', 'Historic Preservation', 'Sacred Gatherings'],
    is_active: true
  },
  {
    id: 'hood-006',
    name: 'Crestview',
    slug: 'crestview',
    description: 'Family-friendly community with emphasis on neighborhood potlucks, skill-sharing, and mutual aid networks.',
    member_count: 276,
    event_count: 29,
    coordinator: 'Alex Chen',
    values: ['Mutual Aid', 'Skill Sharing', 'Family Wellness', 'Community Support'],
    is_active: true
  },
  {
    id: 'hood-007',
    name: 'Domain',
    slug: 'domain',
    description: 'Urban wellness hub with modern healing spaces, rooftop gardens, and tech-conscious holistic practitioners.',
    member_count: 187,
    event_count: 18,
    coordinator: 'River Stone',
    values: ['Modern Wellness', 'Urban Gardens', 'Tech & Spirit', 'Accessibility'],
    is_active: true
  },
  {
    id: 'hood-008',
    name: 'West Lake Hills',
    slug: 'west-lake-hills',
    description: 'Hillside community with panoramic views, private healing retreats, and nature immersion experiences.',
    member_count: 156,
    event_count: 15,
    coordinator: 'Rainbow Moss',
    values: ['Nature Retreats', 'Private Ceremonies', 'Healing Arts', 'Scenic Beauty'],
    is_active: true
  }
];

// Demo messages for community interaction
export const DEMO_MESSAGES = [
  {
    id: 'msg-001',
    from: 'profile-001',
    from_name: 'River Stone',
    to: 'demo-user-001',
    subject: 'Welcome to the community!',
    content: 'Hi Alex! So glad to have you join our wellness community. Looking forward to seeing you at the yoga session!',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    read: true
  },
  {
    id: 'msg-002',
    from: 'profile-003',
    from_name: 'Rainbow Moss',
    to: 'demo-user-001',
    subject: 'Sound Bath Registration Confirmed',
    content: 'Your spot is reserved for the upcoming sound bath ceremony. Please bring a yoga mat and water bottle. See you there!',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    read: false
  }
];

// Demo notifications
export const DEMO_NOTIFICATIONS = [
  {
    id: 'notif-001',
    type: 'event_reminder',
    title: 'Event Tomorrow: Morning Yoga Flow',
    message: 'Don\'t forget about tomorrow\'s yoga session at 7am in Riverside Park!',
    timestamp: new Date().toISOString(),
    read: false
  },
  {
    id: 'notif-002',
    type: 'new_neighbor',
    title: 'New neighbor joined Willow Creek',
    message: 'Welcome Willow Moon to the community! They\'re interested in Tai Chi and meditation.',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    read: true
  }
];

// Alias for backward compatibility
export const DEMO_PEOPLE = DEMO_PROFILES;