// Demo Mode Configuration
export const DEMO_MODE = true; // Set to false to use real Supabase

// Demo user for auto-login
export const DEMO_USER = {
  id: 'demo-user-001',
  email: 'demo@harmonioushabitats.com',
  full_name: 'Alex Chen',
  username: 'alexchen',
  avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  bio: 'Community wellness advocate and meditation practitioner. Passionate about creating sacred spaces for healing and growth.',
  neighborhood: 'Willow Creek',
  holistic_interests: ['Meditation', 'Yoga', 'Sound Healing', 'Breathwork', 'Plant Medicine'],
  verified: true,
  rating: 4.8,
  total_reviews: 42,
  events_attended_count: 28,
  hours_contributed: 156,
  neighbors_met_count: 89
};

// Demo profiles representing diverse community members
export const DEMO_PROFILES = [
  {
    id: 'profile-001',
    email: 'sarah@demo.com',
    full_name: 'Sarah Martinez',
    username: 'sarahm',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    bio: 'Certified yoga instructor and Reiki master. Creating healing spaces for our community.',
    neighborhood: 'Willow Creek',
    holistic_interests: ['Yoga', 'Reiki', 'Crystal Healing', 'Meditation'],
    verified: true,
    rating: 4.9,
    total_reviews: 67
  },
  {
    id: 'profile-002',
    email: 'james@demo.com',
    full_name: 'James Thompson',
    username: 'jamest',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    bio: 'Permaculture enthusiast and community garden coordinator. Let\'s grow together!',
    neighborhood: 'Oak Valley',
    holistic_interests: ['Permaculture', 'Herbalism', 'Sustainable Living'],
    verified: true,
    rating: 4.7,
    total_reviews: 34
  },
  {
    id: 'profile-003',
    email: 'maya@demo.com',
    full_name: 'Maya Patel',
    username: 'mayap',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maya',
    bio: 'Sound healer and meditation guide. Facilitating transformational experiences through vibration.',
    neighborhood: 'Riverside',
    holistic_interests: ['Sound Healing', 'Meditation', 'Kundalini Yoga'],
    verified: true,
    rating: 5.0,
    total_reviews: 89
  },
  {
    id: 'profile-004',
    email: 'david@demo.com',
    full_name: 'David Kim',
    username: 'davidk',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    bio: 'Tai Chi instructor and Traditional Chinese Medicine practitioner.',
    neighborhood: 'Willow Creek',
    holistic_interests: ['Tai Chi', 'Qigong', 'TCM', 'Meditation'],
    verified: true,
    rating: 4.8,
    total_reviews: 56
  },
  {
    id: 'profile-005',
    email: 'luna@demo.com',
    full_name: 'Luna Rodriguez',
    username: 'lunar',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Luna',
    bio: 'Women\'s circle facilitator and moon ceremony guide. Honoring the sacred feminine.',
    neighborhood: 'Garden District',
    holistic_interests: ['Women\'s Circles', 'Moon Ceremonies', 'Sacred Dance'],
    verified: true,
    rating: 4.9,
    total_reviews: 78
  }
];

// Demo events showcasing holistic practices and decentralized community activities
export const DEMO_EVENTS = [
  {
    id: 'event-001',
    title: 'Community Sound Bath & Meditation',
    description: 'Join us for a transformative evening of crystal bowl sound healing and guided meditation. We\'ll create a sacred space for deep relaxation and inner peace. All experience levels welcome.',
    created_by: 'profile-003',
    creator_name: 'Maya Patel',
    event_type: 'sound_healing',
    category: 'wellness',
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days from now
    time: '19:00',
    duration: 90,
    location: 'Harmony Garden Pavilion',
    address: '123 Peace Lane, Willow Creek',
    latitude: 37.7749,
    longitude: -122.4194,
    max_participants: 30,
    current_participants: 18,
    is_free: false,
    price: 20,
    currency: 'Time Credits',
    image_url: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=800',
    tags: ['Sound Healing', 'Meditation', 'Crystal Bowls', 'Relaxation'],
    neighborhood: 'Willow Creek',
    is_virtual: false,
    accessibility_info: 'Wheelchair accessible, mats provided'
  },
  {
    id: 'event-002',
    title: 'Morning Yoga Flow in the Park',
    description: 'Start your day with energizing vinyasa flow yoga surrounded by nature. We\'ll move through sun salutations and standing sequences to awaken body and mind. Bring your own mat.',
    created_by: 'profile-001',
    creator_name: 'Sarah Martinez',
    event_type: 'yoga',
    category: 'wellness',
    date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(), // Tomorrow
    time: '07:00',
    duration: 60,
    location: 'Riverside Park Meadow',
    address: '456 River Road, Riverside',
    latitude: 37.7849,
    longitude: -122.4094,
    max_participants: 25,
    current_participants: 12,
    is_free: true,
    price: 0,
    currency: 'Free',
    image_url: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800',
    tags: ['Yoga', 'Outdoor', 'Morning Practice', 'Vinyasa'],
    neighborhood: 'Riverside',
    is_virtual: false,
    accessibility_info: 'Flat ground, suitable for all levels'
  },
  {
    id: 'event-003',
    title: 'Permaculture Workshop: Food Forest Design',
    description: 'Learn the principles of permaculture and how to design your own food forest. We\'ll cover companion planting, water harvesting, and creating resilient ecosystems in your backyard.',
    created_by: 'profile-002',
    creator_name: 'James Thompson',
    event_type: 'workshop',
    category: 'education',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days from now
    time: '14:00',
    duration: 180,
    location: 'Community Garden Center',
    address: '789 Green Way, Oak Valley',
    latitude: 37.7649,
    longitude: -122.4294,
    max_participants: 20,
    current_participants: 15,
    is_free: false,
    price: 35,
    currency: 'Time Credits',
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    tags: ['Permaculture', 'Sustainability', 'Gardening', 'Food Security'],
    neighborhood: 'Oak Valley',
    is_virtual: false,
    accessibility_info: 'Garden paths are gravel, some uneven terrain'
  },
  {
    id: 'event-004',
    title: 'Women\'s New Moon Circle',
    description: 'Gather in sacred sisterhood to honor the new moon. We\'ll share intentions, practice ritual, and support each other\'s journey. A safe space for feminine wisdom and healing.',
    created_by: 'profile-005',
    creator_name: 'Luna Rodriguez',
    event_type: 'ceremony',
    category: 'spiritual',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 1 week from now
    time: '19:30',
    duration: 120,
    location: 'Sacred Space Studio',
    address: '321 Moon Street, Garden District',
    latitude: 37.7549,
    longitude: -122.4394,
    max_participants: 12,
    current_participants: 8,
    is_free: false,
    price: 15,
    currency: 'Time Credits',
    image_url: 'https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=800',
    tags: ['Women\'s Circle', 'Moon Ceremony', 'Ritual', 'Sacred Feminine'],
    neighborhood: 'Garden District',
    is_virtual: false,
    accessibility_info: 'Intimate setting, cushions provided'
  },
  {
    id: 'event-005',
    title: 'Tai Chi for Beginners',
    description: 'Discover the gentle power of Tai Chi. Learn basic movements and principles of this ancient practice for balance, flexibility, and inner calm. Perfect for all ages.',
    created_by: 'profile-004',
    creator_name: 'David Kim',
    event_type: 'movement',
    category: 'wellness',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days from now
    time: '09:00',
    duration: 60,
    location: 'Willow Creek Community Center',
    address: '555 Center Drive, Willow Creek',
    latitude: 37.7749,
    longitude: -122.4094,
    max_participants: 15,
    current_participants: 6,
    is_free: true,
    price: 0,
    currency: 'Free',
    image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800',
    tags: ['Tai Chi', 'Movement', 'Balance', 'Mindfulness'],
    neighborhood: 'Willow Creek',
    is_virtual: false,
    accessibility_info: 'Indoor space, chair options available'
  },
  {
    id: 'event-006',
    title: 'Community Potluck & Skill Share',
    description: 'Bring a dish to share and a skill to teach! This monthly gathering celebrates our diverse talents. Past shares included knitting, fermentation, music, and healing techniques.',
    created_by: 'demo-user-001',
    creator_name: 'Alex Chen',
    event_type: 'gathering',
    category: 'community',
    date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), // 4 days from now
    time: '18:00',
    duration: 150,
    location: 'Neighborhood Commons',
    address: '999 Community Lane, Willow Creek',
    latitude: 37.7749,
    longitude: -122.4194,
    max_participants: 50,
    current_participants: 32,
    is_free: true,
    price: 0,
    currency: 'Free',
    image_url: 'https://images.unsplash.com/photo-1540914124281-342587941389?w=800',
    tags: ['Potluck', 'Skill Share', 'Community', 'Networking'],
    neighborhood: 'Willow Creek',
    is_virtual: false,
    accessibility_info: 'Fully accessible venue with ramps'
  },
  {
    id: 'event-007',
    title: 'Virtual Breathwork Journey',
    description: 'Join us online for a powerful breathwork session. Using conscious connected breathing, we\'ll release stored emotions and access expanded states of consciousness.',
    created_by: 'profile-001',
    creator_name: 'Sarah Martinez',
    event_type: 'breathwork',
    category: 'wellness',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days from now
    time: '20:00',
    duration: 75,
    location: 'Online via Zoom',
    address: 'Virtual Event',
    latitude: null,
    longitude: null,
    max_participants: 100,
    current_participants: 45,
    is_free: false,
    price: 10,
    currency: 'Time Credits',
    image_url: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4a7?w=800',
    tags: ['Breathwork', 'Virtual', 'Healing', 'Consciousness'],
    neighborhood: 'Global',
    is_virtual: true,
    accessibility_info: 'Closed captions available, recording provided'
  },
  {
    id: 'event-008',
    title: 'Herbal Medicine Making Workshop',
    description: 'Learn to make your own herbal tinctures, teas, and salves. We\'ll work with locally sourced plants and discuss their healing properties. Take home your creations!',
    created_by: 'profile-002',
    creator_name: 'James Thompson',
    event_type: 'workshop',
    category: 'education',
    date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(), // 6 days from now
    time: '13:00',
    duration: 120,
    location: 'The Herb Garden',
    address: '234 Plant Path, Oak Valley',
    latitude: 37.7649,
    longitude: -122.4294,
    max_participants: 12,
    current_participants: 10,
    is_free: false,
    price: 45,
    currency: 'Time Credits',
    image_url: 'https://images.unsplash.com/photo-1509909756405-be0199881695?w=800',
    tags: ['Herbalism', 'DIY', 'Natural Medicine', 'Workshop'],
    neighborhood: 'Oak Valley',
    is_virtual: false,
    accessibility_info: 'Standing workshop, stools available'
  },

  // Austin-specific local events
  {
    id: 'event-009',
    title: 'Barton Springs Full Moon Swim & Ceremony',
    description: 'Join us for a sacred full moon swim at Barton Springs Pool. We\'ll gather for intention setting, take a moonlit swim in the natural spring waters, and close with a gratitude circle.',
    created_by: 'profile-003',
    creator_name: 'Maya Patel',
    event_type: 'ceremony',
    category: 'spiritual',
    date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    time: '20:00',
    duration: 120,
    location: 'Barton Springs Pool',
    address: '2201 Barton Springs Rd, Austin, TX 78746',
    latitude: 30.2640,
    longitude: -97.7706,
    max_participants: 40,
    current_participants: 28,
    is_free: false,
    price: 15,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1518972559570-7cc1309f3229?w=800',
    tags: ['Full Moon', 'Swimming', 'Ceremony', 'Barton Springs'],
    neighborhood: 'Zilker',
    is_virtual: false,
    accessibility_info: 'Pool has accessible entry, bring towels'
  },
  {
    id: 'event-010',
    title: 'East Austin Community Garden Workday',
    description: 'Help us maintain our community garden! We\'ll be planting seasonal vegetables, building raised beds, and sharing gardening wisdom. Fresh produce goes to local families.',
    created_by: 'profile-002',
    creator_name: 'James Thompson',
    event_type: 'gardening',
    category: 'community',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    time: '09:00',
    duration: 180,
    location: 'Boggy Creek Community Garden',
    address: '2015 E 12th St, Austin, TX 78702',
    latitude: 30.2712,
    longitude: -97.7281,
    max_participants: 50,
    current_participants: 23,
    is_free: true,
    price: 0,
    currency: 'Free',
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    tags: ['Gardening', 'Community', 'Sustainability', 'East Austin'],
    neighborhood: 'East Austin',
    is_virtual: false,
    accessibility_info: 'Garden paths are wheelchair accessible'
  },
  {
    id: 'event-011',
    title: 'Sunset Ecstatic Dance at Mount Bonnell',
    description: 'Dance freely as the sun sets over Lake Austin! We start with gentle movement, build to ecstatic expression, and end with a silent meditation overlooking the city.',
    created_by: 'profile-005',
    creator_name: 'Luna Rodriguez',
    event_type: 'dance',
    category: 'movement',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    time: '18:30',
    duration: 120,
    location: 'Mount Bonnell',
    address: '3800 Mt Bonnell Rd, Austin, TX 78731',
    latitude: 30.3211,
    longitude: -97.7726,
    max_participants: 30,
    current_participants: 19,
    is_free: false,
    price: 25,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=800',
    tags: ['Ecstatic Dance', 'Sunset', 'Mount Bonnell', 'Movement'],
    neighborhood: 'West Austin',
    is_virtual: false,
    accessibility_info: 'Stairs to overlook, alternative viewing area available'
  },
  {
    id: 'event-012',
    title: 'South Congress Farmers Market Meditation',
    description: 'Start your Saturday with a grounding meditation at the SoCo farmers market. We\'ll practice mindful breathing, then explore the market with conscious awareness.',
    created_by: 'profile-004',
    creator_name: 'David Kim',
    event_type: 'meditation',
    category: 'mindfulness',
    date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    time: '08:00',
    duration: 45,
    location: 'SoCo Farmers Market',
    address: '1826 S Congress Ave, Austin, TX 78704',
    latitude: 30.2481,
    longitude: -97.7494,
    max_participants: 20,
    current_participants: 14,
    is_free: true,
    price: 0,
    currency: 'Free',
    image_url: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800',
    tags: ['Meditation', 'Farmers Market', 'South Congress', 'Mindfulness'],
    neighborhood: 'South Congress',
    is_virtual: false,
    accessibility_info: 'Flat terrain, shaded area available'
  },
  {
    id: 'event-013',
    title: 'Greenbelt Nature Therapy Walk',
    description: 'Experience the healing power of nature with a guided forest bathing walk through the Greenbelt. We\'ll practice mindful observation, tree meditation, and creek-side reflection.',
    created_by: 'profile-001',
    creator_name: 'Sarah Martinez',
    event_type: 'nature_therapy',
    category: 'wellness',
    date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    time: '10:00',
    duration: 150,
    location: 'Barton Creek Greenbelt',
    address: '3755 S Capital of Texas Hwy, Austin, TX 78704',
    latitude: 30.2459,
    longitude: -97.8081,
    max_participants: 15,
    current_participants: 11,
    is_free: false,
    price: 30,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    tags: ['Forest Bathing', 'Nature Therapy', 'Greenbelt', 'Hiking'],
    neighborhood: 'Barton Hills',
    is_virtual: false,
    accessibility_info: 'Moderate trail, not wheelchair accessible'
  },
  {
    id: 'event-014',
    title: 'Mueller Lake Park Tai Chi',
    description: 'Join our weekly Tai Chi practice at Mueller Lake Park. We practice the 24-form Yang style, perfect for beginners and experienced practitioners alike.',
    created_by: 'profile-004',
    creator_name: 'David Kim',
    event_type: 'tai_chi',
    category: 'movement',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    time: '07:30',
    duration: 60,
    location: 'Mueller Lake Park',
    address: '4550 Mueller Blvd, Austin, TX 78723',
    latitude: 30.2969,
    longitude: -97.7055,
    max_participants: 35,
    current_participants: 22,
    is_free: true,
    price: 0,
    currency: 'Free',
    image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800',
    tags: ['Tai Chi', 'Mueller', 'Morning Practice', 'Qigong'],
    neighborhood: 'Mueller',
    is_virtual: false,
    accessibility_info: 'Flat surface, wheelchair accessible'
  },
  {
    id: 'event-015',
    title: 'Lady Bird Lake SUP Yoga',
    description: 'Practice yoga on a stand-up paddleboard! We\'ll start with basic SUP skills, then flow through gentle yoga poses while floating on Lady Bird Lake.',
    created_by: 'profile-001',
    creator_name: 'Sarah Martinez',
    event_type: 'yoga',
    category: 'movement',
    date: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    time: '17:00',
    duration: 90,
    location: 'Texas Rowing Center',
    address: '1541 W Cesar Chavez St, Austin, TX 78703',
    latitude: 30.2747,
    longitude: -97.7628,
    max_participants: 12,
    current_participants: 10,
    is_free: false,
    price: 45,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
    tags: ['SUP Yoga', 'Lady Bird Lake', 'Water Yoga', 'Paddleboard'],
    neighborhood: 'Downtown',
    is_virtual: false,
    accessibility_info: 'Must be able to swim, life jackets provided'
  },
  {
    id: 'event-016',
    title: 'Crestview Community Potluck & Song Circle',
    description: 'Bring a dish to share and your voice! We\'ll enjoy a community meal followed by an acoustic song circle. All instruments and skill levels welcome.',
    created_by: 'profile-002',
    creator_name: 'James Thompson',
    event_type: 'gathering',
    category: 'community',
    date: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(),
    time: '18:00',
    duration: 180,
    location: 'Brentwood Park',
    address: '6710 Arroyo Seco, Austin, TX 78757',
    latitude: 30.3378,
    longitude: -97.7311,
    max_participants: 60,
    current_participants: 34,
    is_free: true,
    price: 0,
    currency: 'Bring a dish',
    image_url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800',
    tags: ['Potluck', 'Music', 'Community', 'Crestview'],
    neighborhood: 'Crestview',
    is_virtual: false,
    accessibility_info: 'Park pavilion is wheelchair accessible'
  },
  {
    id: 'event-017',
    title: 'Domain Northside Crystal Bowl Healing',
    description: 'Experience deep relaxation with crystal singing bowls at the Domain. We\'ll create a sonic sanctuary for stress release and energetic alignment.',
    created_by: 'profile-003',
    creator_name: 'Maya Patel',
    event_type: 'sound_healing',
    category: 'wellness',
    date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    time: '19:30',
    duration: 75,
    location: 'Domain NORTHSIDE Park',
    address: '11410 Century Oaks Terrace, Austin, TX 78758',
    latitude: 30.3958,
    longitude: -97.7238,
    max_participants: 25,
    current_participants: 18,
    is_free: false,
    price: 35,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=800',
    tags: ['Crystal Bowls', 'Sound Healing', 'Domain', 'Meditation'],
    neighborhood: 'Domain',
    is_virtual: false,
    accessibility_info: 'Indoor venue, elevator access available'
  },
  {
    id: 'event-018',
    title: 'Zilker Botanical Garden Mindful Photography',
    description: 'Explore the beauty of Zilker Botanical Garden through mindful photography. Learn to see with fresh eyes and capture the essence of nature\'s patterns.',
    created_by: 'profile-005',
    creator_name: 'Luna Rodriguez',
    event_type: 'workshop',
    category: 'creative',
    date: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000).toISOString(),
    time: '09:00',
    duration: 120,
    location: 'Zilker Botanical Garden',
    address: '2220 Barton Springs Rd, Austin, TX 78746',
    latitude: 30.2689,
    longitude: -97.7723,
    max_participants: 15,
    current_participants: 12,
    is_free: false,
    price: 40,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=800',
    tags: ['Photography', 'Mindfulness', 'Zilker', 'Nature'],
    neighborhood: 'Zilker',
    is_virtual: false,
    accessibility_info: 'Paved paths throughout garden'
  },
  {
    id: 'event-019',
    title: 'Hyde Park Fire Ceremony & Storytelling',
    description: 'Gather around the sacred fire for an evening of storytelling and release. Bring something to symbolically release into the fire and a story to share.',
    created_by: 'profile-002',
    creator_name: 'James Thompson',
    event_type: 'ceremony',
    category: 'spiritual',
    date: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    time: '19:00',
    duration: 150,
    location: 'Private Garden Hyde Park',
    address: '4400 Ave B, Austin, TX 78751',
    latitude: 30.3074,
    longitude: -97.7335,
    max_participants: 20,
    current_participants: 16,
    is_free: false,
    price: 20,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800',
    tags: ['Fire Ceremony', 'Storytelling', 'Hyde Park', 'Ritual'],
    neighborhood: 'Hyde Park',
    is_virtual: false,
    accessibility_info: 'Backyard setting, some uneven ground'
  },
  {
    id: 'event-020',
    title: 'Rainey Street Sunrise Breathwork',
    description: 'Start your day with powerful breathwork overlooking Lady Bird Lake from Rainey Street. We\'ll practice pranayama techniques for energy and clarity.',
    created_by: 'profile-004',
    creator_name: 'David Kim',
    event_type: 'breathwork',
    category: 'wellness',
    date: new Date(Date.now() + 13 * 24 * 60 * 60 * 1000).toISOString(),
    time: '06:30',
    duration: 60,
    location: 'Rainey Street District',
    address: '295 Rainey St, Austin, TX 78701',
    latitude: 30.2587,
    longitude: -97.7390,
    max_participants: 25,
    current_participants: 17,
    is_free: true,
    price: 0,
    currency: 'Donation-based',
    image_url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    tags: ['Breathwork', 'Sunrise', 'Rainey Street', 'Pranayama'],
    neighborhood: 'Rainey District',
    is_virtual: false,
    accessibility_info: 'Rooftop location with elevator access'
  }
];

// Demo spaces for community sharing
export const DEMO_SPACES = [
  {
    id: 'space-001',
    name: 'Springdale Farm Community Pavilion',
    description: 'Historic urban farm pavilion surrounded by organic gardens. Perfect for farm-to-table dinners, workshops, and healing ceremonies.',
    type: 'outdoor_pavilion',
    capacity: 30,
    address: '755 Springdale Rd, Austin, TX 78702',
    neighborhood: 'East Austin',
    amenities: ['Electricity', 'Restrooms', 'Garden Access', 'Sound System'],
    availability: 'Weekends and evenings',
    is_free: false,
    price_per_hour: 25,
    currency: 'Time Credits',
    created_by: 'profile-003',
    host_name: 'Maya Patel',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    rating: 4.9,
    total_bookings: 156
  },
  {
    id: 'space-002',
    name: 'Casa de Luz Healing Studio',
    description: 'Intimate studio at Casa de Luz wellness center designed for healing work, small circles, and spiritual practices. Features altar space and natural lighting.',
    type: 'studio',
    capacity: 12,
    address: '1701 Toomey Rd, Austin, TX 78704',
    neighborhood: 'South Congress',
    amenities: ['Yoga Props', 'Sound Equipment', 'Altar Space', 'Tea Kitchen'],
    availability: 'Daily 8am-9pm',
    is_free: false,
    price_per_hour: 15,
    currency: 'Time Credits',
    created_by: 'profile-005',
    host_name: 'Luna Rodriguez',
    image_url: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800',
    rating: 5.0,
    total_bookings: 89
  },
  {
    id: 'space-003',
    name: 'Mueller Community Garden Greenhouse',
    description: 'Year-round growing space with workshop area in the sustainable Mueller development. Great for permaculture education and hands-on learning.',
    type: 'greenhouse',
    capacity: 20,
    address: '4550 Mueller Blvd, Austin, TX 78723',
    neighborhood: 'Mueller',
    amenities: ['Water Access', 'Tools', 'Seating', 'Whiteboard'],
    availability: 'Weekdays and Saturday mornings',
    is_free: true,
    price_per_hour: 0,
    currency: 'Free',
    created_by: 'profile-002',
    host_name: 'James Thompson',
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    rating: 4.7,
    total_bookings: 234
  }
];

// Demo neighborhoods representing Austin communities
export const DEMO_NEIGHBORHOODS = [
  {
    id: 'hood-001',
    name: 'East Austin',
    slug: 'east-austin',
    description: 'Vibrant creative community known for urban farming, art studios, and community gardens. Strong focus on sustainability and local food systems.',
    member_count: 456,
    event_count: 42,
    coordinator: 'James Thompson',
    values: ['Community Gardens', 'Art & Culture', 'Sustainability', 'Local Food'],
    is_active: true
  },
  {
    id: 'hood-002',
    name: 'South Congress',
    slug: 'south-congress',
    description: 'Eclectic neighborhood blending wellness studios, farmers markets, and conscious businesses. Home to many holistic practitioners.',
    member_count: 389,
    event_count: 38,
    coordinator: 'Sarah Martinez',
    values: ['Wellness', 'Local Business', 'Mindfulness', 'Creative Expression'],
    is_active: true
  },
  {
    id: 'hood-003',
    name: 'Zilker',
    slug: 'zilker',
    description: 'Nature-centered community near Barton Springs and the Greenbelt. Focus on outdoor wellness, environmental protection, and sacred ceremonies.',
    member_count: 412,
    event_count: 35,
    coordinator: 'Maya Patel',
    values: ['Nature Connection', 'Sacred Water', 'Environmental Care', 'Outdoor Wellness'],
    is_active: true
  },
  {
    id: 'hood-004',
    name: 'Mueller',
    slug: 'mueller',
    description: 'Modern sustainable community with parks, community gardens, and wellness spaces. Emphasis on green living and mindful development.',
    member_count: 298,
    event_count: 26,
    coordinator: 'David Kim',
    values: ['Sustainable Living', 'Community Health', 'Green Spaces', 'Innovation'],
    is_active: true
  },
  {
    id: 'hood-005',
    name: 'Hyde Park',
    slug: 'hyde-park',
    description: 'Historic neighborhood with strong community bonds, home gatherings, and storytelling traditions. Focus on intergenerational wisdom.',
    member_count: 234,
    event_count: 22,
    coordinator: 'Luna Rodriguez',
    values: ['Community Wisdom', 'Storytelling', 'Historic Preservation', 'Sacred Gatherings'],
    is_active: true
  },
  {
    id: 'hood-006',
    name: 'Crestview',
    slug: 'crestview',
    description: 'Family-friendly community with emphasis on neighborhood potlucks, skill-sharing, and mutual aid networks.',
    member_count: 276,
    event_count: 29,
    coordinator: 'Alex Chen',
    values: ['Mutual Aid', 'Skill Sharing', 'Family Wellness', 'Community Support'],
    is_active: true
  },
  {
    id: 'hood-007',
    name: 'Domain',
    slug: 'domain',
    description: 'Urban wellness hub with modern healing spaces, rooftop gardens, and tech-conscious holistic practitioners.',
    member_count: 187,
    event_count: 18,
    coordinator: 'Sarah Martinez',
    values: ['Modern Wellness', 'Urban Gardens', 'Tech & Spirit', 'Accessibility'],
    is_active: true
  },
  {
    id: 'hood-008',
    name: 'West Lake Hills',
    slug: 'west-lake-hills',
    description: 'Hillside community with panoramic views, private healing retreats, and nature immersion experiences.',
    member_count: 156,
    event_count: 15,
    coordinator: 'Maya Patel',
    values: ['Nature Retreats', 'Private Ceremonies', 'Healing Arts', 'Scenic Beauty'],
    is_active: true
  }
];

// Demo messages for community interaction
export const DEMO_MESSAGES = [
  {
    id: 'msg-001',
    from: 'profile-001',
    from_name: 'Sarah Martinez',
    to: 'demo-user-001',
    subject: 'Welcome to the community!',
    content: 'Hi Alex! So glad to have you join our wellness community. Looking forward to seeing you at the yoga session!',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    read: true
  },
  {
    id: 'msg-002',
    from: 'profile-003',
    from_name: 'Maya Patel',
    to: 'demo-user-001',
    subject: 'Sound Bath Registration Confirmed',
    content: 'Your spot is reserved for the upcoming sound bath ceremony. Please bring a yoga mat and water bottle. See you there!',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    read: false
  }
];

// Demo notifications
export const DEMO_NOTIFICATIONS = [
  {
    id: 'notif-001',
    type: 'event_reminder',
    title: 'Event Tomorrow: Morning Yoga Flow',
    message: 'Don\'t forget about tomorrow\'s yoga session at 7am in Riverside Park!',
    timestamp: new Date().toISOString(),
    read: false
  },
  {
    id: 'notif-002',
    type: 'new_neighbor',
    title: 'New neighbor joined Willow Creek',
    message: 'Welcome David Kim to the community! They\'re interested in Tai Chi and meditation.',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    read: true
  }
];

// Alias for backward compatibility
export const DEMO_PEOPLE = DEMO_PROFILES;