name: Fancy Discord Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send fancy Discord embed
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"embeds\": [{
                   \"title\": \"🚀 New push by ${{ github.actor }}\",
                   \"description\": \"**${COMMIT_MESSAGE}**\",
                   \"color\": 5814783,
                   \"url\": \"${COMMIT_URL}\",
                   \"footer\": { \"text\": \"${{ github.repository }} on branch ${{ github.ref_name }}\" },
                   \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
                 }],
                 \"components\": [{
                   \"type\": 1,
                   \"components\": [{
                     \"type\": 2,
                     \"label\": \"🔗 View Commit\",
                     \"style\": 5,
                     \"url\": \"${COMMIT_URL}\"
                   }]
                 }]
               }" \
               ${{ secrets.DISCORD_WEBHOOK }}

